# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x08grpcdemo\"C\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"B\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"1\n\x0cStockRequest\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"0\n\rStockResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t2Q\n\x10InventoryService\x12=\n\nCheckStock\x12\x16.grpcdemo.StockRequest\x1a\x17.grpcdemo.StockResponse2O\n\x0cOrderService\x12?\n\x0cProcessOrder\x12\x16.grpcdemo.OrderRequest\x1a\x17.grpcdemo.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=28
  _globals['_ORDERREQUEST']._serialized_end=95
  _globals['_ORDERRESPONSE']._serialized_start=97
  _globals['_ORDERRESPONSE']._serialized_end=163
  _globals['_STOCKREQUEST']._serialized_start=165
  _globals['_STOCKREQUEST']._serialized_end=214
  _globals['_STOCKRESPONSE']._serialized_start=216
  _globals['_STOCKRESPONSE']._serialized_end=264
  _globals['_INVENTORYSERVICE']._serialized_start=266
  _globals['_INVENTORYSERVICE']._serialized_end=347
  _globals['_ORDERSERVICE']._serialized_start=349
  _globals['_ORDERSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
