# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocessor.proto\x12\tprocessor\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"/\n\x0c\x44\x61taResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x01\n\rDataProcessor\x12@\n\x0bProcessData\x12\x16.processor.DataRequest\x1a\x17.processor.DataResponse\"\x00\x12\x41\n\nStreamData\x12\x16.processor.DataRequest\x1a\x17.processor.DataResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=30
  _globals['_DATAREQUEST']._serialized_end=60
  _globals['_DATARESPONSE']._serialized_start=62
  _globals['_DATARESPONSE']._serialized_end=109
  _globals['_DATAPROCESSOR']._serialized_start=112
  _globals['_DATAPROCESSOR']._serialized_end=260
# @@protoc_insertion_point(module_scope)
